-- Convert Programme.category from a fixed enum into an admin-managed
-- ProgrammeCategory table, preserving existing Programme rows' category
-- assignments. Written by hand (not autogenerated) because Prisma's default
-- diff for this change is destructive (drops the column, has no way to
-- backfill a required FK from an enum column) — see AGENTS.md/session notes.

-- 1. Add the new FK column, nullable for now so we can backfill it.
ALTER TABLE "Programme" ADD COLUMN "categoryId" TEXT;

-- 2. Backfill categoryId from the existing enum column before it's dropped.
UPDATE "Programme" SET "categoryId" = CASE "category"
  WHEN 'ENGINEERING_TECHNOLOGY' THEN 'engineering-technology'
  WHEN 'BUSINESS_ECONOMICS' THEN 'business-economics'
  WHEN 'LAW_EDUCATION' THEN 'law-education'
  WHEN 'STUDY_ABROAD' THEN 'study-abroad'
END;

-- 3. Drop the old index/column that depend on the enum, then the enum type
-- itself, so the "ProgrammeCategory" name is free for the new table.
DROP INDEX "Programme_category_isPublished_idx";
ALTER TABLE "Programme" DROP COLUMN "category";
DROP TYPE "ProgrammeCategory";

-- 4. Create the new admin-managed lookup table.
CREATE TABLE "ProgrammeCategory" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProgrammeCategory_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ProgrammeCategory_name_key" ON "ProgrammeCategory"("name");
CREATE UNIQUE INDEX "ProgrammeCategory_slug_key" ON "ProgrammeCategory"("slug");
CREATE INDEX "ProgrammeCategory_orderIndex_idx" ON "ProgrammeCategory"("orderIndex");

-- 5. Seed the 4 categories that used to be the fixed enum values, using the
-- same literal ids the backfill above assumed.
INSERT INTO "ProgrammeCategory" ("id", "name", "slug", "orderIndex", "createdAt", "updatedAt") VALUES
  ('engineering-technology', 'Engineering & Technology', 'engineering-technology', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('business-economics', 'Business & Economics', 'business-economics', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('law-education', 'Law & Education', 'law-education', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('study-abroad', 'Study Abroad', 'study-abroad', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 6. Now that every Programme row has a valid categoryId, enforce NOT NULL
-- and add the FK + composite index.
ALTER TABLE "Programme" ALTER COLUMN "categoryId" SET NOT NULL;
ALTER TABLE "Programme" ADD CONSTRAINT "Programme_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ProgrammeCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "Programme_categoryId_isPublished_idx" ON "Programme"("categoryId", "isPublished");
